spring:
  devtools:
    livereload:
      port: 0
      enabled: false
    add-properties: false
  r2dbc:
    url: r2dbc:mariadb://192.168.1.251:3306/fm3base
    username: dbuser
    password: 367Qh7dzNB
    
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh
    enabled-by-default: true


debug: false

logging:
  # level:
  #   org.springframework.r2dbc: debug
  #   ru.gkmirep.fm3geozone.controllers.GeoZoneController: debug
  file:
    name: /logs/fm3-geozone.log
    
# server:
#   port: 8086
