spring:
  cloud:
    gateway:
      routes:
        - id: wbd-trip-service
          uri: lb://wbd-trip-service
          predicates:
            - Path=/trips/**
          filters:
            - RewritePath=/trips/?(?<segment>.*),/$\{segment}
          metadata:
            response-timeout: 200000
            connect-timeout: 200000

# management:
#   endpoints:
#     web:
#       exposure:
#         include: *
  
server:
  port: 7070

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
  instance:
    prefer-ip-address: true
      
debug: false
logging:
  file:
    # path: ./logs
    name: ./logs/gateway-1.log
  level:
    org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler: debug
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: debug
