spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://192.168.1.41:8888
  cloud:
    gateway:
      routes:
        - id: wbd-trip-service
          uri: lb://wbd-trip-service
          predicates:
            - Path=/trips/**
          filters:
            - RewritePath=/trips/?(?<segment>.*),/$\{segment}
          metadata:
            response-timeout: 20000000
            connect-timeout: 200000

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh
    
server:
  port: 7070

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
  instance:
    prefer-ip-address: true
      
debug: false
logging:
  file:
    name: /logs/gateway.log
  level:
    org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler: debug
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: debug
