spring:
  devtools:
    livereload:
      port: 0
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      host: 192.168.1.41
      port: 27017
      username: mirep
      password: cWlp40To
      database: maBase
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
  instance:
    prefer-ip-address: true

debug: false

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh
#server:
#  port: 8091

mirep:
  api-keys:
    ya-routing-key: 6696e47a-f4c1-4952-a787-74aa9d6c074f
    dadata-key: 114a85ebdd1df1be9fb1a6670e06e834cab468d0
    secret-key: 1e7dfc2798fd8aa424ca60d9ce3ba64d1c6ac9d2
  paths:
    reports: ./reports
  services-url:
    ya-routing": https://api.routing.yandex.net/v2
    dadata-geocoding: https://cleaner.dadata.ru/api/v1/clean/address
    dadata-reverse-geocoding: http://suggestions.dadata.ru/suggestions/api/4_1/rs
logging:
  level:
    org.springframework.data.mongodb: info
    org.springframework.web.reactive.function.client: info
    ru.gkmirep.core.utils.ExUtils: info
    ru.gkmirep.geoservice.controllers.ReverseGeoCodingController: debug
    ru.gkmirep.geoservice.services.YandexRoutingService: debug
    ru.gkmirep.geoservice.controllers.ru.gkmirep.geoservice.controllers.RouteController: info
  file:
    name: logs\geoservice.log
