spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://wbd-trip-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/?(?<segment>.*),/$\{segment}
          metadata:
            response-timeout: 2000000
            connect-timeout: 200000
        - id: wbd-trip-service
          uri: lb://wbd-trip-service
          predicates:
            - Path=/trips/**
          filters:
            - RewritePath=/trips/?(?<segment>.*),/$\{segment}
          metadata:
            response-timeout: 2000000
            connect-timeout: 200000
        - id: pepsico-tms-service
          uri: lb://pepsico-tms
          predicates:
            - Path=/pepsico/**
          filters:
            - RewritePath=/pepsico/?(?<segment>.*),/$\{segment}
          metadata:
            response-timeout: 2000000
            connect-timeout: 200000
        - id: object-service
          uri: lb://object-service
          predicates:
            - Path=/objects/**
          filters:
            - RewritePath=/objects/?(?<segment>.*),/$\{segment}
          metadata:
            response-timeout: 200000
            connect-timeout: 200000
        - id: pepsico-points
          uri: lb://pepsico-points
          predicates:
            - Path=/pepsico-point/**
          filters:
            - RewritePath=/pepsico-point/?(?<segment>.*),/$\{segment}
          metadata:
            response-timeout: 200000
            connect-timeout: 200000
        - id: plants
          uri: lb://wbd-plant-service
          predicates:
            - Path=/plants/**
          filters:
            - RewritePath=/plants/?(?<segment>.*),/$\{segment}
          metadata:
            response-timeout: 20000
            connect-timeout: 20000
        - id: rm-supplier
          uri: lb://raw-milk-supplier
          predicates:
            - Path=/rm-supplier/**
          filters:
            - RewritePath=/rm-supplier/?(?<segment>.*),/$\{segment}
          metadata:
            response-timeout: 20000
            connect-timeout: 20000
            
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh
    
server:
  port: 7070

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
  instance:
    prefer-ip-address: true
      
debug: false
logging:
  file:
    name: /logs/gateway.log
  level:
    org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler: debug
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: debug
