spring:
  mongodb:
    host: 192.168.1.41
    port: 27017
    username: mirep
    password: cWlp40To
    database: dev-ma-base

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
  instance:
    prefer-ip-address: true

kafka:
  hosts: 192.168.1.41:9092
  consumer:
    group: mail-service-consumer
    trusted: '*'
  topics:



mirep:
  paths:
    uploads: ./shpt
  logging:
    events-kafka-producer-service: TRACE
    mail-receiving-service: TRACE
    settings-handler: TRACE
    scheduled-mail-reading-service: TRACE

logging:
  level:
    ru.gkmirep.mail_service.kafka.EventsKafkaProducerService: trace
    ru.gkmirep.mail_service.services.receiving.MailReceivingService: trace
    ru.gkmirep.mail_service.services.scheduler.ScheduledMailReadingService: trace
  file:
    name: ../logs/mail-service.log
