spring:
  devtools:
    livereload:
      port: 0
    add-properties: false
  data:
    redis:
      host: 192.168.1.41
      port: 6379
      command-timeout: 10000 #ms
    mongodb:
      host: 192.168.1.41
      port: 27017
      username: mirep
      password: cWlp40To
      database: maBase
  r2dbc:
    host: 192.168.1.251
    port: 3306
    database: extm1base
    username: dbuser
    password: 367Qh7dzNB


debug: false


cassandra:
  host: 192.168.1.110
  port: 9042
  keyspace-name: telematics
  username: mirep
  password: daPi-oLW4g


kafka:
  read-all-data: false
  max-message-size: 5242880
  hosts: 192.168.1.41:9092
  consumer-group: object-service
  topics:
    object-topic: object-create-event-topic
    object-edit-topic: edit-object-topic
    object-new-topic: new-object-topic
    object-delete-topic: delete-object-topic
    new-processed-data: new-processed-data-topic
  trusted: 'ru.gkmirep.core.telematics, ru.gkmirep.core.dtos.objects.object'

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
  instance:
    prefer-ip-address: true

mirep:
  mem-table:
    max-days-in-mem: 7
  debug:
    record-raw-data: false
  route:
    point-limit: 30000
    expire-timeout: 48
  move-state:
    min-speed: 5
    min-dist: 100
    ign-analyze: true
  validate-object:
    max-speed: 300
    max-dist: 10000
    min-sat-count: 4
  services-url:
    xlsx-parsing-service: http://xlsx-parsing-service/v1

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh

logging:
  level:    
    org.springframework.r2dbc: info
    org.springframework.web.reactive.function.client: info
    org.springframework.data.mongodb: info
    ru.gkmirep.object_service.controllers.ObjectGroupController: info
    ru.gkmirep.object_service.controllers.ObjectController: info
    ru.gkmirep.object_service.controllers.TelematicsDataController: debug
    ru.gkmirep.object_service.mappers.ObjectMapperService: info
    ru.gkmirep.object_service.kafka.TelematicsDataKafkaConsumerService: debug
    ru.gkmirep.object_service.kafka.ObjectKafkaConsumerService: debug
    ru.gkmirep.object_service.kafka.producers.ProcessedTelematicsDataKafkaProducerService: info
    ru.gkmirep.object_service.services.object.ObjectService: info
    ru.gkmirep.object_service.services.processing.ObjectProcessingService: info
    ru.gkmirep.object_service.services.sql.TelematicsDataMemSqlQueryService: info
    ru.gkmirep.object_service.services.sql.ObjectMemorySQLQueryService: info
    ru.gkmirep.object_service.listeners.TelematicsDataEventListenerService: info
  file:
    name: logs/object-service.log


