spring:
  devtools:
    livereload:
      port: 0
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      host: 192.168.1.41
      port: 27017
      username: mirep
      password: cWlp40To
      database: maBase
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
  instance:
    prefer-ip-address: true

kafka:
  group-id: pepsico-point
  trusted: "*"
  hosts: 192.168.1.41:9092
  topics:
    pepsico-point-create: pepsico-point-create-topic
    pepsico-point-edit: pepsico-point-edit-topic
    pepsico-point-delete: pepsico-point-delete-topic
    pepsico-point-new: pepsico-point-new-topic



debug: false

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh

mirep:
  paths:
    reports: ./reports
  services-url:
    geo-service: lb://geoservice/v1
logging:
  level:
    org.springframework.data.mongodb: info
    org.springframework.web.reactive.function.client: info
    ru.gkmirep.core.utils.ExUtils: debug
    ru.gkmirep.pepsico_points.controllers.PepsicoPointLocationDtoController: debug
  file:
    name: logs/pepsico-points.log
