spring:
  devtools:
    livereload:
      port: 0
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: 192.168.1.41
      port: 6379
      command-timeout: 1000 #ms
    mongodb:
      host: 192.168.1.41
      port: 27017
      username: mirep
      password: cWlp40To
      database: maBase



eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
  instance:
    prefer-ip-address: true

debug: false

kafka:
  hosts: 192.168.1.41:9092
  consumer-group: pepsico-tms-consumer
  topics:
    object-topic: object-create-event-topic
    telematics-data: new-processed-data-topic
    new-object-topic: new-object-topic
    edit-object-topic: edit-object-topic
    delete-object-topic: delete-object-topic
    pepsico-point-edit-topic: pepsico-point-edit-topic
    pepsico-point-new: pepsico-point-new-topic
  trusted: '*'


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh


mirep:
  trip:
    hours-offset-to-complete: 40
  route:
    request-interval: 10800
  debug:
    record-raw-ptd: false
  companyId: 6792600a234f205704c0a076
  paths:
    reports: ./reports
    uploads: ./shpt
  services-url:
    xlsx-parsing-service: lb://xlsx-parsing-service/v1/pepsico
    geo-service: lb://geoservice/v1
    pepsico-point-service: lb://pepsico-points/v1/pepsico/point/dto/location
    object-service: lb://object-service/v1
logging:
  level:
    org.springframework.data.mongodb: info
    org.springframework.web.reactive.function.client: info
    ru.gkmirep.core.utils.ExUtils: debug
    ru.gkmirep.pepsico_tms.controllers.PepsicoMonitoringTripsController: debug
    ru.gkmirep.pepsico_tms.mappers.v1.PepsicoTripMapperService: info
    ru.gkmirep.pepsico_tms.mappers.v2.trip.services.TripParsingMappingService: trace
    ru.gkmirep.pepsico_tms.dtos.v1.monitoring_trip.VehicleState: info
    ru.gkmirep.pepsico_tms.kafka.point.PepsicoPointKafkaConsumerService: trace
    ru.gkmirep.pepsico_tms.kafka.TelematicsDataKafkaConsumerService: info
    ru.gkmirep.pepsico_tms.kafka.object.ObjectKafkaProducerService: info
    ru.gkmirep.pepsico_tms.kafka.object.ObjectKafkaConsumerService: debug
    ru.gkmirep.pepsico_tms.listeners.ProcessedTelematicsDataEventListener: debug
    ru.gkmirep.pepsico_tms.services.v1.https_services.PepsicoPointService: trace
    ru.gkmirep.pepsico_tms.services.v1.object.ObjectService: trace
    ru.gkmirep.pepsico_tms.services.v1.redis.TripInMemoryService: trace
    ru.gkmirep.pepsico_tms.services.v1.trips.TripParsingService: trace
    ru.gkmirep.pepsico_tms.services.v1.trips.MonitoringTripsService: trace
    ru.gkmirep.pepsico_tms.services.v1.trips.PepsicoTripService: trace
    ru.gkmirep.pepsico_tms.services.v1.trips.ProcessingTripService: trace
    ru.gkmirep.pepsico_tms.services.v2.http.HttpObjectService: trace
    ru.gkmirep.pepsico_tms.services.v2.redis.PepsicoPointRedisService: trace
    ru.gkmirep.pepsico_tms.services.v2.report.TripReportService: trace
    ru.gkmirep.pepsico_tms.services.v2.processing.TripCalculatingServiceImpl: trace
    ru.gkmirep.pepsico_tms.services.v2.processing.TripProcessingServiceImpl: trace
    ru.gkmirep.pepsico_tms.services.v2.TripsParsingService: trace
    ru.gkmirep.trip_lib.services.TripMemService: trace
    ru.gkmirep.trip_lib.services.TripRedisService: trace
    ru.gkmirep.trip_lib.services.TripProcessingService: trace
    ru.gkmirep.trip_lib.services.TripManageService: trace
  file:
    name: logs/pepsico-tms.log
  # logback:
  #   rollingpolicy:
  #     max-file-size: 100MB
