spring:
  devtools:
    livereload:
      port: 0
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: 192.168.1.41
      port: 6379
      command-timeout: 1000 #ms
    mongodb:
      host: 192.168.1.41
      port: 27017
      username: mirep
      password: cWlp40To
      database: maBase



eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
  instance:
    prefer-ip-address: true

debug: false

kafka:
  hosts: 192.168.1.41:9092
  consumer-group: pepsico-tms-consumer
  topics:
    object-topic: object-create-event-topic
  trusted: '*'


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh


mirep:
  route:
    request-interval: 60
  debug:
    record-raw-ptd: false
  companyId: 6792600a234f205704c0a076
  paths:
    reports: ./reports
  services-url:
    xlsx-parsing-service: lb://xlsx-parsing-service/v1/pepsico
    geo-service: lb://geoservice/v1
    pepsico-point-service: lb://pepsico-points/v1/pepsico/point/dto/location
    object-service: lb://object-service/v1
logging:
  level:
    org.springframework.data.mongodb: info
    org.springframework.web.reactive.function.client: info
    ru.gkmirep.core.utils.ExUtils: debug
    ru.gkmirep.pepsico_tms.controllers.PepsicoMonitoringTripsController: trace
    ru.gkmirep.pepsico_tms.mappers.PepsicoTripMapperService: info
    ru.gkmirep.pepsico_tms.dtos.monitoring_trip.VehicleState: info
    ru.gkmirep.pepsico_tms.kafka.PepsicoPointKafkaConsumerService: info
    ru.gkmirep.pepsico_tms.kafka.TelematicsDataKafkaConsumerService: trace
    ru.gkmirep.pepsico_tms.kafka.object.ObjectKafkaProducerService: info
    ru.gkmirep.pepsico_tms.kafka.object.ObjectKafkaConsumerService: debug
    ru.gkmirep.pepsico_tms.listeners.ProcessedTelematicsDataEventListener: debug
    ru.gkmirep.pepsico_tms.services.https_services.PepsicoPointService: trace
    ru.gkmirep.pepsico_tms.services.https_services.HttpObjectService: trace
    ru.gkmirep.pepsico_tms.services.object.ObjectService: trace
    ru.gkmirep.pepsico_tms.services.redis.TripInMemoryService: trace
    ru.gkmirep.pepsico_tms.services.trips.TripParsingService: trace
    ru.gkmirep.pepsico_tms.services.trips.MonitoringTripsService: trace
    ru.gkmirep.pepsico_tms.services.trips.PepsicoTripService: trace
    ru.gkmirep.pepsico_tms.services.trips.ProcessingTripService: trace
  file:
    name: logs\pepsico-tms.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
