spring:
  devtools:
    livereload:
      port: 0
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      host: 192.168.1.41
      port: 27017
      username: mirep
      password: cWlp40To
      database: maBase
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
  instance:
    prefer-ip-address: true

debug: false

kafka:
  hosts: 192.168.1.41:9092
  consumer-group: pepsico-tms-consumer
  topics:
    object-topic: object-create-event-topic
  trusted: ru.gkmirep.core.dtos.pepsico_point


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh


mirep:
  companyId: 6792600a234f205704c0a076
  paths:
    reports: ./reports
  services-url:
    xlsx-parsing-service: http://xlsx-parsing-service/v1/pepsico
    geo-service: http://geoservice/v1
    pepsico-point-service: lb://pepsico-points/v1/pepsico/point/dto/location
    object-service: lb://object-sercie/v1
logging:
  level:
    org.springframework.data.mongodb: info
    org.springframework.web.reactive.function.client: info
    ru.gkmirep.core.utils.ExUtils: debug
    ru.gkmirep.pepsico_tms.services.https_services.PepsicoPointService: debug
    ru.gkmirep.pepsico_tms.mappers.PepsicoTripMapperService: debug
    ru.gkmirep.pepsico_tms.services.trips.PepsicoTripService: debug
    ru.gkmirep.pepsico_tms.services.trips.PepsicoMonitoringTripsService: debug
    ru.gkmirep.pepsico_tms.controllers.PepsicoMonitoringTripsController: debug
  file:
    name: logs\pepsico-tms.log
