spring:
  devtools:
    livereload:
      port: 0
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: 192.168.1.41
      port: 6379
      command-timeout: 30000 #ms
    mongodb:
      host: 192.168.1.41
      port: 27017
      username: mirep
      password: cWlp40To
      database: maBase

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
    refresh:
      enable: true
  instance:
    prefer-ip-address: true

debug: false

kafka:
  hosts: 192.168.1.41:9092
  consumer:
    consumer-group: raw-milk-tms
  topics:
    wbd-plant-compact-dto-create: wbd-plant-compact-dto-create
    wbd-plant-compact-dto-change: wbd-plant-compact-dto-change
    wbd-plant-create: wbd-plant-create-event-topic
    wbd-plant-change: wbd-plant-change-event-topic
    wbd-plant-delete: wbd-plant-delete-event-topic
    create: ""
    change: ""
    delete: ""
  trusted: '*'


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh


mirep:
  companyId: 6792602e234f205704c0a077
  trip-monitoring:
    recalculation-period: 1200
  services-url:
    xlsx-parsing-service: lb://xlsx-parsing-service/v1
    supplier-service: lb://raw-milk-supplier/v1
    plant-service: lb://wbd-plant-service/v1
    object-service: lb://object-service/v1
    geo-service: lb://geoservice/v1
    
logging:
  level:
    org.springframework.web.reactive.function.client: info
    org.springframework.data.mongodb: info
    ru.gkmirep.raw_milk_tms.mapper.TripParsingMappingService: trace
    ru.gkmirep.raw_milk_tms.mapper.TripMonitoringMappingService: trace
    ru.gkmirep.raw_milk_tms.kafka.PlantKafkaConsumer: trace
    ru.gkmirep.raw_milk_tms.service.http_service.HttpSupplierService: trace
    ru.gkmirep.raw_milk_tms.service.http_service.HttpPlantService: trace
    ru.gkmirep.raw_milk_tms.service.http_service.HttpObjectService: trace
    ru.gkmirep.raw_milk_tms.service.mongo.TripMongoService: trace
    ru.gkmirep.raw_milk_tms.service.redis.SupplierRedisService: trace
    ru.gkmirep.raw_milk_tms.service.redis.PlantRedisService: trace
    ru.gkmirep.raw_milk_tms.service.redis.ObjectRedisService: trace
    ru.gkmirep.raw_milk_tms.service.redis.TripRedisService: trace
    ru.gkmirep.raw_milk_tms.service.redis.TripMemoryService: trace
    ru.gkmirep.raw_milk_tms.service.TripMonitoringService: trace
    ru.gkmirep.raw_milk_tms.service.TripProcessingService: trace
    ru.gkmirep.raw_milk_tms.service.TripService: trace
  file:
    name: logs\raw-milk-tms.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
