spring:
  devtools:
    livereload:
      port: 0
    add-properties: false


eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
  instance:
    prefer-ip-address: true
    
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh


logging:
  level:
    ru.gkmirep.core.utils.ExUtils: info
    ru.gkmirep.telematics_parser.sockets.TelematicsMessageHandler: info
    ru.gkmirep.telematics_parser.services.wialon.WialonIPSParserV2_0: info
    ru.gkmirep.telematics_parser.services.wialon.WialonIPSParserV1_1: info
    ru.gkmirep.telematics_parser.services.wialon.WialonIPSParser: info
    ru.gkmirep.telematics_parser.services.egts.EgtsParser: info
    ru.gkmirep.telematics_parser.kafka.TelematicsDataProducerKafkaService: info
    ru.gkmirep.telematics_parser.listeners.TelematicsDataListenerComponent: info
  file:
    name: logs/telematics-parsing.log

mirep:
  listening-port: 2026
  connection-accept-timeout: 120
  sleeping-time: 1000
  thread-pool-size: 5000
  data-waiting_time: 1800

kafka:
  hosts: 192.168.1.41:9092
  topics:
    telematics-data: new-telematics-data
