spring:
  devtools:
    livereload:
      port: 0
      enabled: false
    add-properties: false
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: 192.168.1.41
      port: 6379
      timeout: 10000
      pool-size: 100
  mongodb:
    host: 192.168.1.41
    port: 27017
    username: mirep
    password: cWlp40To
    database: maBase
  r2dbc:
    host: 192.168.1.251
    port: 3306
    database: extm1base
    #    url: r2dbc:mariadb://192.168.1.251:3306/extm1base
    username: dbuser
    password: 367Qh7dzNB

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
  instance:
    prefer-ip-address: true
    
debug: false

# server:
#   port: 8088

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh
kafka:
  hosts: 192.168.1.41:9092
  consumer:
    group: wbd-trip-consumer
    trusted: '*'
  topics:
    new: wbd-sp-creating-topic
    change: wbd-sp-changing-topic
    delete: wbd-sp-deleting-topic
    create-sp: wbd-new-sp-topic
    new-cd: wbd-cd-creating-topic
    change-cd: wbd-cd-changing-topic
    delete-cd: wbd-cd-deleting-topic
    new-branch: wbd-branch-creating-topic
    change-branch: wbd-branch-changing-topic
    delete-branch: wbd-branch-deleting-topic
  
mirep:
  key: 10601ddaf98891270d42b937053b7249c2dfdb1695462a18dbc77637bd4c941d
  paths:
    reports: ./reports
    uploads: ./shpt

  services-url:
    sale-point-service_v1: lb://sale-point-service/v1
    sale-point-service: lb://sale-point-service/v2
    branch-service: lb://wbd-branch-service/v1
    cross-dock-service_v1: lb://wbd-cross-dock-service/v1
    cross-dock-service: lb://wbd-cross-dock-service/v2
    fm3-object-service: lb://fm3-object-service/v1
    fm3-telematics-data-service: lb://fm3-telematics-data-service/v1
    xlsx-parsing-service: lb://xlsx-parsing-service/v1
    wbd-plant-service: lb://wbd-plant-service/v1
    object-service: lb://object-service/v1
    geo-service: lb://geoservice/v1
  logging:
    #services
    HttpWbdBranchService: TRACE
    HttpWbdCrossDockService: TRACE
    cross-dock-redis-service: TRACE
    BranchRedisService: TRACE
    BranchMappingService: TRACE
    branch-redis-service: TRACE
    redis-sale-point-service: TRACE
    http-sale-point-service: TRACE
    http-vehicle-service: TRACE
    redis-vehicle-service: TRACE
    http-object-service: TRACE
    fm3-object-service: TRACE
    http-geo-service: TRACE
    sale_points_kafka_producer_service: INFO
    fm3-telematics-service: INFO
    telematics-data-service: INFO
    trip-calculating-service: INFO
    trip-mapping-service: INFO
    trip-migration-service: INFO
    trip-mongo-service-1: INFO
    sale_points_kafka_consumer_service: INFO
    sale_point_redis_mapping_service: INFO
    trip-report-mapping-service: INFO
    trips-reports-service: INFO
    trips-reports-handler: INFO
    trips-utils-handler: INFO
    trips-parsing-handler: INFO
    telematics-service: INFO
    trip-route-handler: INFO
    trip-management-service: INFO
    cross-dock-kafka-consumer-service: INFO
    shpt-kafka-consumer-service: TRACE
logging:
  level:
    org.springframework.r2dbc: info
    org.springframework.data.mongodb: info
    org.springframework.web.reactive.function.client: info
    ru.gkmirep.tripservice.controllers.TripController: debug
    ru.gkmirep.tripservice.controllers.TripsMonitoringReportController: debug
    ru.gkmirep.tripservice.kafka.sale_points.consumer.SalePointsKafkaConsumerService: trace
    ru.gkmirep.tripservice.kafka.sale_points.producer.SalePointsKafkaProducerService: trace
    ru.gkmirep.tripservice.kafka.shpt.ShptKafkaConsumerService: trace
    ru.gkmirep.tripservice.mappers.trip.TripMapperService: debug
    ru.gkmirep.tripservice.services.http_services.Fm3ObjectService: info
    ru.gkmirep.tripservice.services.http_services.SalePointService: info
    ru.gkmirep.tripservice.services.http_services.CrossDockService: info
    ru.gkmirep.tripservice.services.http_services.Fm3TelematicsDataService: info
    ru.gkmirep.tripservice.services.rdbc.TripServiceRDBC: info
    ru.gkmirep.tripservice.services.trip.TripService: info
    ru.gkmirep.tripservice.services.trip.TripReportService: info
    ru.gkmirep.tripservice.services.trip.TripStatesService: info
    ru.gkmirep.tripservice.services.trip.WbdSHPTTripService: info
    ru.gkmirep.tripservice.services.trip.WbdMonitoringReportService: info
    ru.gkmirep.tripservice.services.trip.WbdTempReportService: info
    ru.gkmirep.tripservice.services.http_services.XlsxParsingService: info
    ru.gkmirep.tripservice.services.XlsxReportService: debug
    ru.gkmirep.core.utils.ExUtils: info
  file:
    name: /logs/trip-service.log
