spring:
  devtools:
    livereload:
      port: 0
    add-properties: false
  data:
    mongodb:
      host: 192.168.1.41
      port: 27017
      username: mirep
      password: cWlp40To
      database: maBase

debug: true

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
  instance:
    prefer-ip-address: true
    
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh


mirep:
  services-url:
    xlsx-parsing-service: lb://xlsx-parsing-service/v1
    geo-service: lb://geoservice/v1
logging:
  level:
    org.springframework.web.reactive.function.client: info
    org.springframework.data.mongodb: info
    ru.gkmirep.wbd_plant.controllers.WbdPlantController: info
  file:
    name: logs/wbd-plant.log

kafka:
  hosts: 192.168.1.41:9092
  consumer:
    group: wbd-plant-consumer
    trusted: ru.gkmirep.core.dtos.wbd_plant
  topics:
    compact-dto-create: wbd-plant-compact-dto-create
    compact-dto-change: wbd-plant-compact-dto-change
    wbd-plant-create: wbd-plant-create-event-topic
    wbd-plant-change: wbd-plant-change-event-topic
    wbd-plant-delete: wbd-plant-delete-event-topic


