server:
  port: 8084

spring:
  rsocket:
    server:
      transport: websocket
      mapping-path: /rsocket
  r2dbc:
    url: r2dbc:mariadb://192.168.1.251:3306/extm1base
    username: dbuser
    password: 367Qh7dzNB
  data:
    mongodb:
      host: 192.168.1.41
      port: 27017
      username: mirep
      password: cWlp40To
      database: maBase
  devtools:
    livereload:
      port: 0
      enabled: false
    add-properties: false
  threads:
    virtual:
      enabled: true

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: refresh
    enabled-by-default: true

debug: false

logging:
  file:
    name: /logs/wbd-warehouse.log
  # level:
  #   org.springframework.r2dbc: debug
  #   org.springframework.web.reactive.function.client: debug
  #   ru.gkmirep.wbdwarehouseservice.services.WarehouseService: debug
  #   ru.gkmirep.wbdwarehouseservice.services.Fm3GeoZoneService: debug
