spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mariadb://192.168.1.251:3306/extm1base
    driver-class-name: org.mariadb.jdbc.Driver
    username: dbuser
    password: 367Qh7dzNB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
server:
  port: 9093
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.41:9999/eureka/
