server:
  port: 9091

spring:
  threads:
    virtual:
      enabled: true

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
  instance:
    prefer-ip-address: true

