server:
  port: 9091

spring:
  threads:
    virtual:
      enabled: true

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: *
    enabled-by-default: true

logging:
  file:
    path: ./logs
    name: xlsx-service
xlsx:
  upload_path: ./upload
  shpt_path: =./shpt
