server:
  port: 9091

spring:
  devtools:
    livereload:
      port: 0
      enabled: false
    add-properties: false
  threads:
    virtual:
      enabled: true

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.41:9999/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: refresh
    enabled-by-default: true

logging:
  level:
    ru.gkmirep.xlsxparsingservice.services.PepsicoTMSXLSXParsingService: trace
  file:
    name: /logs/xlsx-service.log

mirep:
  logging:
    #controllers
    PepsicoXlsxParsingController: INFO
    #services
    XlsxParsingService: INFO
    PepsicoTMSXLSXParsingService: INFO


xlsx:
  upload-path: ./upload
  shpt-path: ./shpt

debug: false

